url: "https://xpayclient.lgdacom.net/xpay/Gateway.do"
test_url: "https://xpayclient.lgdacom.net:7443/xpay/Gateway.do"
aux_url: "http://xpay.lgdacom.net:7080/xpay/Gateway.do"
server_id: <%= ENV.fetch("SERVER_ID") { "01" } %>
timeout: 60
verify_cert: false
verify_host: false
report_error: true
auto_rollback: true
mert_id: "lgdacomxpay"
mert_key: <%= ENV.fetch("MERT_KEY") { "live_key" } %>
test_mert_id: "tlgdacomxpay"
test_mert_key: <%= ENV.fetch("TEST_MERT_KEY") { "test_key" } %>
test_mode: true
